CREATE DATABASE BOOK_DEALER;

USE BOOK_DEALER;

CREATE TABLE AUTHOR(
    author_id INT,
    name VARCHAR(20),
    city VARCHAR(20),
    country VARCHAR(20),
    PRIMARY KEY(author_id)
);

CREATE TABLE PUBLISHER(
    publisher_id INT,
    name VARCHAR(20),
    city VARCHAR(20),
    country VARCHAR(20),
    PRIMARY KEY(publisher_id)
);

CREATE TABLE CATEGORY(
    category_id INT,
    description VARCHAR(40),
    PRIMARY KEY(category_id)
);

CREATE TABLE CATALOG(
    book_id INT,
    title VARCHAR(20),
    author_id INT,
    publisher_id INT,
    category_id INT,
    year INT,
    price INT,
    PRIMARY KEY(book_id),
    FOREIGN KEY(author_id) REFERENCES AUTHOR(author_id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY(publisher_id) REFERENCES PUBLISHER(publisher_id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY(category_id) REFERENCES CATEGORY(category_id) ON DELETE SET NULL ON UPDATE CASCADE
);

 CREATE TABLE ORDER_DETAILS(
    order_no INT,
    book_id INT,
    quantity INT,
    PRIMARY KEY(order_no)
);

ALTER TABLE ORDER_DETAILS ADD CONSTRAINT  cat_fk FOREIGN KEY(book_id) REFERENCES CATALOG(book_id) ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO AUTHOR VALUES(1001,'TERAS CHAN','CA','USA');
INSERT INTO AUTHOR VALUES(1002,'STEVENS','ZOMBI','UGANDA');
INSERT INTO AUTHOR VALUES(1003,'M MANO','CAIR','CANADA');
INSERT INTO AUTHOR VALUES(1004,'KARTHIK B.P.','NEW YORK','USA');
INSERT INTO AUTHOR VALUES(1005,'WILLIAM STALLINGS','LAS VEGAS','USA');

INSERT INTO PUBLISHER VALUES(1,'PEARSON','NEW YORK','USA');
INSERT INTO PUBLISHER VALUES(2,'EEE','NEW SOUTH VALES','USA');
INSERT INTO PUBLISHER VALUES(3,'PHI','DELHI','INDIA');
INSERT INTO PUBLISHER VALUES(4,'WILLEY','BERLIN','GERMANY');
INSERT INTO PUBLISHER VALUES(5,'MGH','NEW YORK','USA');

INSERT INTO CATEGORY VALUES(1001,'COMPUTER SCIENCE');
INSERT INTO CATEGORY VALUES(1002,'ALGORITHM DESIGN');
INSERT INTO CATEGORY VALUES(1003,'ELECTRONICS');
INSERT INTO CATEGORY VALUES(1004,'PROGRAMMING');
INSERT INTO CATEGORY VALUES(1005,'OPERATING SYSTEMS'); 

INSERT INTO CATALOG VALUES(11,'Unix System Prg',1001,1,1001,2000,251);
INSERT INTO CATALOG VALUES(12,'Digital Signals',1002,2,1003,2001,425);
INSERT INTO CATALOG VALUES(13,'Logic Design',1003,3,1002,1999,225);
INSERT INTO CATALOG VALUES(14,'Server Prg',1004,4,1004,2001,333);
INSERT INTO CATALOG VALUES(15,'Linux OS',1005,5,1005,2003,326);
INSERT INTO CATALOG VALUES(16,'C++ Bible',1005,5,1001,2000,526);
INSERT INTO CATALOG VALUES(17,'COBOL Handbook',1005,4,1001,2000,658);

INSERT INTO ORDER_DETAILS VALUES(1,11,5);
INSERT INTO ORDER_DETAILS VALUES(2,12,8);
INSERT INTO ORDER_DETAILS VALUES(3,13,15);
INSERT INTO ORDER_DETAILS VALUES(4,14,22);
INSERT INTO ORDER_DETAILS VALUES(5,15,3);
INSERT INTO ORDER_DETAILS VALUES(6,17,10);

SELECT a.author_id,a.name,a.city,a.country,c.price FROM AUTHOR a,CATALOG c
WHERE a.author_id=c.author_id
AND c.year>2000
GROUP BY c.author_id
HAVING COUNT(c.author_id)>=2;

SELECT a.name FROM AUTHOR a,CATALOG c,ORDER_DETAILS o
WHERE a.author_id=c.author_id
AND c.book_id=o.book_id
AND o.quantity=(SELECT MAX(quantity) FROM ORDER_DETAILS);

UPDATE CATALOG c 
SET c.price=1.1*c.price
WHERE c.publisher_id=(SELECT publisher_id FROM PUBLISHER WHERE name="PEARSON");
